export const BASE_URL = 'http://localhost:3001'
export const ACCOUNTS = 'accounts'
export const GET_ACCOUNTS = 'accounts/getAccounts'
export const JOURNAL_ENTRY = 'journalEntry/create-entry'
export const GET_JOURNAL_ENTRY = 'journalEntry/current-entries'
export const GET_TRIAL_BALANCE = 'trialBalance'
export const GET_BALANCE_SHEET = 'generateBalanceSheet'
export const GET_OWNER_EQUITY = 'generateOwnerEquityStatement'